on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop','main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
            DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker-compose build
      - name: List docker image
        run: docker image ls 
      - name: Tagin back
        run: docker tag klockan-frontend:v1 klockan/frontend:v1 
      - name: Push to
        run: docker push klockan/frontend:v1 
